- enhancd.sh
```
$ $SHELL --version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ source enhancd.sh
bash: enhancd.sh: line 572: syntax error near unexpected token `local'
bash: enhancd.sh: line 572: `    local t'
```
> Fix syntax error in bash

- enhancd.sh
There is a bug which freezes the console when calling cd::cd in first.  
It happens when treating the content of a log file which has no size.
Other solution is to avoid calling makelog with no argument.  
However, it might be `worse` because this bug also relates with other functions (e.g. 'reverse' and 'unique'.).
cf. [https://github.com/b4b4r07/enhancd/commit/9b4c6518415f11ad75f9a8025934a0a9b3e5ab4f](https://github.com/b4b4r07/enhancd/commit/9b4c6518415f11ad75f9a8025934a0a9b3e5ab4f)
> Fixed a freezing bug which relates with the size of log

- enhancd.sh
I used your awesome library on bash.
This works great!
However, when I used your awesome library on zsh, features which relate with an interactive grep did not work fine.
Zsh does not split a given statement into words by delimiters (e.g. half-width whitespace) if no options. [1]
So Zsh treats `$ENHANCD_FILTER` as one statement if it's replaced each semicolons with a half-width space.
This causes unexpected errors.
`SH_WORD_SPLIT` option can solve this bug.
This patch makes this option enable in only local function scope.
\[1] [http://zsh.sourceforge.net/FAQ/zshfaq03.html](http://zsh.sourceforge.net/FAQ/zshfaq03.html)
> Fixed a bug when splitting string on zsh

- enhancd.sh
- test/enhancd_test.sh
Show #18 .
Fixed following case,
```sh
mkdir -p /foo/com.foo/baz
cd /foo/com.foo/baz
cd .. # then, select 'foo'
```
> Fixed jumping to conclusions when 'cd ..'

- enhancd.sh
I have this alias in my config
`cp='cp -iv'`
and every time I cd to a directory I receive a message like this
```
‘/home/k1/.enhancd/enhancd.log’ -> ‘/home/k1/.enhancd/enhancd.backup’
‘/home/k1/.enhancd/enhancd.04041608405063961462’ -> ‘/home/k1/.enhancd/enhancd.log’
‘/home/k1/.enhancd/enhancd.log’ -> ‘/home/k1/.enhancd/enhancd.backup’
‘/home/k1/.enhancd/enhancd.040416084050639617392’ -> ‘/home/k1/.enhancd/enhancd.log’
‘/home/k1/.enhancd/enhancd.log’ -> ‘/home/k1/.enhancd/enhancd.backup’
‘/home/k1/.enhancd/enhancd.040416084051639630319’ -> ‘/home/k1/.enhancd/enhancd.log
```  
this commit solves the issue by using absolute path and avoiding any alias may have been defined by user
> Use absolute path to avoid user alias

- src/share/get_dirstep.awk
Fix the following error:
```
awk: extra ] at source line 4 source file ~/.zplug/repos/b4b4r07/enhancd/src/share/get_dirstep.awk
context is
>>>  gsub(/\/[^/] <<< 
awk: nonterminated character class \/[^
source line number 4 source file ~/.zplug/repos/b4b4r07/enhancd/src/share/get_dirstep.awk
```
My enviroment is OS X 10.11, and awk version 20070501.
> Add escape in gsub

- README.md
- src/share/split_path.awk
- test/enhancd-enhancd_test.sh
I added the ENHANCD_DOT_SHOW_FULLPATH environment variable at #42 .
But there is a bug when the current directory includes the same directory name set:
```console
% pwd
/home/lisa/home/work
% cd ..
1: /
2: /home
3: /home/lisa
4: /home
```
I fixed this bug by changing the logic of `src/share/split_path.awk`.
My environment:
mawk 1.3.3 Nov 1996, Ubuntu 16.04
> Fix wrong directory name when ENHANCD_DOT_SHOW_FULLPATH=1

- init.sh
Fix issue that init routine runs in global scope. (Especially, setopt influences global environment.)
> Fix issue that init routine runs in global scope

- init.sh
Should fix this error: __enhancd::init::init:unalias:23: no such hash table element: cd
If ENHANCD_COMMAND is not set, or is not set to cd
> Unalias error

- init.sh
for satrt up speed issue
In my environment, original enhancd takes 22ms to load.
```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
num  calls                time                       self            name
-----------------------------------------------------------------------------------
1)    9         165.33    18.37   99.91%     45.99     5.11   27.79%  loadlib
2)    1          27.30    27.30   16.50%     26.93    26.93   16.27%  _zsh_highlight_load_highlighters
3)    1          26.18    26.18   15.82%     26.18    26.18   15.82%  _zsh_highlight_bind_widgets
4)    1          22.43    22.43   13.56%     22.33    22.33   13.49%  __enhancd::init::init
5)    2          15.41 …
```
> add: skip mkdir and touch if exist

- init.sh
- src/filter.sh
`setopt localoptions SH_WORD_SPLIG` is unneeded, because shwordsplit isn't enabled in global environment.
Instead `eval` command use to execute the `$filter` command.
In fact, this script below didn't work I expected.
```zsh
export ENHANCD_FILTER="fzf-tmux -u 10%:peco:fzf"
zplug "b4b4r07/enhancd", use:init.sh
```
```zsh
❯ cd
__enhancd::filter::interactive:28: command not found: fzf-tmux -d 10%
```
Because the line (`setopt localoptions SH_WORD_SPLIT`) means `shwordsplit` only enable in local: `__enhancd::init::init()`. But `$filter` command is executed at `__enhancd::filter::interactive()` function. So `shwordsplit` is disabled at that time.
`shwordsplit` enabled in global, for example execute `setopt SH_WORD_SPLIT`. But if `shwordsplit` is set in global, whole shell environment may be …
> Fix that shwordsplit doesn't work properly.

- init.sh
- src/arguments.sh
- src/filter.sh
- src/path.sh
- src/utils.sh
This patch makes the used awk version dynamic. On FreeBSD, if gawk (GNU awk) is found it is used else awk is selected. For other OSes it's always awk.
This removes these errors when used with some other plugins:
awk: i/o error occurred while closing /dev/stdin
source line number 3
> FreeBSD awk throws errors if the fifos are closed too early

- src/cd.sh
```console
$ mkdir "foo bar baz"
$ cd foo\ bar\ baz
__enhancd::cd::builtin:cd:10: too many arguments
```
> Fix builtin cd arguments

- functions/_enhancd_filter_interactive.fish
If no directory is selected in fuzzy list, `cd` to the current directory
When aborting a fuzzy selection on fish (i.e : pressing `esc` key when fuzzy list is opened), nothing is sent as argument to `cd`, so it comes back to `~/`, which is not the excpected behaviour
> Fix cd back to ~/ when aborting fuzzy selection with fish shell

- conf.d/enhancd.fish
- init.fish
- init.sh
Don't delete bash sources when installing with fish (and vice versa) 
It's an unexpected behavior, and causes issues when using multiple shell (#123)
> Prevent sources deletion

- conf.d/enhancd.fish
- functions/_enhancd_filepath_abs.fish
- functions/_enhancd_filepath_list_step.fish
- functions/_enhancd_filepath_split.fish
- functions/_enhancd_filter_fuzzy.fish
- functions/_enhancd_filter_reverse.fish
- functions/_enhancd_flag_print_help.fish
- functions/_enhancd_help.fish
- functions/_enhancd_ltsv_parse.fish
Update awk scripts paths in fish functions
6d07e5af842d14e1b903cbc43e38f60316295426 fixed awk scripts paths in bash/zsh sources, but messed up with ones in fish functions, assuming that `ENHANCD_ROOT` was set to the fish config directory, which is wrong.
In fish sources, `$ENHANCD_ROOT` points to `$fisher_path/functions/enhancd`, with `$fisher_path` being set to `$__fish_config_dir` by default, but can be customized by the user.
> Fix awk scripts paths in fish functions

- conf.d/enhancd.fish
fisher does not expose the `fisher_path` variable to plugins, so the plugin root directory must be derived from the executed file path.
When trying to use enhancd I get this error:
```
> cd somewhere
awk: can't open file /functions/enhancd/lib/fuzzy.awk
```
See https://github.com/jorgebucaran/fisher/issues/643
and example fix in tide: https://github.com/IlanCosman/tide/pull/65/files#diff-03d14d12bce8e3fa8a268acb8958f88c88c631f13f6f33312b6cc249ab7742a6R9
> fish: do not rely on fisher variable to find the plugin root

- functions/_enhancd_filepath_abs.fish
When trimming newlines from the `dir` variable using `string trim` the original variable is mistakenly left unmodified.
When running `cd ..` I'm getting:
```
awk: newline in string /Users/.../... at source line 1
```
> Fix trailing newline in variable passed to awk when changing to relative path

- functions/_enhancd_cd_after.fish
- functions/_enhancd_filepath_abs.fish
- functions/_enhancd_source_default.fish
Fix some issues in fish:
* Literal `\n`s in history entries.
* Parent traversal via `..` doesn't work because `filepath_abs` doesn't properly trim the newline character. After the newline that is still there gets translated by fish to a space (via IFS), it results in the `dir` variable having an extra trailing space. The resulting string isn't a real path, so the awk script fails on it.
Directories with spaces end up showing with literal `\n`s, like:
```
/Users/.../VirtualBox\nVMs
```
And `..` doesn't work.
> Fish fixes

- conf.d/enhancd.fish
- functions/_enhancd_alias.fish
Use function instead of alias in Fish, for better speed.
Also fix error when user installs the plugin.
```
kid ~> fisher install b4b4r07/enhancd
fisher install version 4.1.0
Fetching https://codeload.github.com/b4b4r07/enhancd/tar.gz/HEAD
Installing b4b4r07/enhancd
(omitted)
alias: Body cannot be empty
Installed 1 plugin/s
```
> Use function instead of alias in Fish

- functions/_enhancd_command_grep.fish
- functions/_enhancd_filter_exclude_gitignore.fish
- functions/_enhancd_filter_fuzzy.fish
- functions/_enhancd_filter_join.fish
- functions/_enhancd_filter_reverse.fish
- functions/_enhancd_filter_unique.fish
- functions/_enhancd_history_open.fish
- functions/_enhancd_ltsv_open.fish
- functions/_enhancd_ltsv_parse.fish
- functions/enhancd/lib/split.awk
- init.sh
- src/cd.sh
- src/command.sh
- src/completion.zsh
- src/filepath.sh
- src/filter.sh
- src/history.sh
- src/ltsv.sh
Update https://github.com/b4b4r07/enhancd/pull/136.
(Write the motivation why you submit this pull request)
As written in https://github.com/b4b4r07/enhancd/pull/136, the display is broken if built-in commands have an alias on it.
In addition to `cat`, we have also added prefixes for `awd`, `sed`, `basename`, and `dirname`.
(based on https://github.com/b4b4r07/enhancd/pull/136#issuecomment-737693844)
> Use `command` prefix in built-in command

- README.md
- Fix anchor link for `#configuration*s*` in README.
- Currently it does not work.
> Make README toc link work

- functions/_enhancd_cd_before.fish
- src/cd.sh
Reverts b4b4r07/enhancd#165
Performance issue
Sometimes cd hanged due to copying backup files..
> Revert "Take backup before running cd command"

- README.md
Added information on how to setup enhancd for zsh + oh-my-zsh
Thought it will be useful for people who don't use zplug.
> docs: added installation information for oh-my-zsh

- functions/_enhancd_cd_builtin.fish
In fish, running `cd foobar` will cd to the home directory (effectively running `cd` with no arguments) if the target directory does not exist. The same behavior happens if `Ctrl-C` or `Esc` is pressed while the fuzzy search is open.
Related: #161 
This fix will make enhancd default to the working directory if no arguments are passed in, since args is only empty when there is an error. 
Fix suggested by @Gorthog in #161
> fish: Do not change directory if Ctrl-C pressed in fuzzy search

- functions/enhancd/lib/fuzzy.awk
- Escaping ([ref](https://qiita.com/ko1nksm/items/a22c0ce88e39c9f2dcb0))
- Declaring "lines" as an array to avoid ambiguity ([ref](https://www.nixcraft.com/t/how-to-use-awk-regex-as-match-variable-passed-from-shell/3669))
To fix #189
> Fix awk error

- README.md
- docs/piping.tape
- src/cd.sh
Add this feature
Originally, enhancd had this feature. But the feature was only available in one directory. This time, I will make it support multiple lines.
> Allow to pipe multiple dirs to cd

- functions/enhancd/lib/fuzzy.awk
- functions/enhancd/lib/has_dup_lines.awk
- functions/enhancd/lib/help.awk
- functions/enhancd/lib/ltsv.awk
- functions/enhancd/lib/reverse.awk
- functions/enhancd/lib/split.awk
- functions/enhancd/lib/step_by_step.awk
- functions/enhancd/lib/to_abspath.awk
Format. So `git diff -w` is nothing
Make two indents the same as shell scripts
> Format awk scripts

- README.md
- functions/enhancd.fish
- functions/enhancd/lib/help.awk
- src/cd.sh
Add new label `format` to config.ltsv. 
To format custom input
```tsv
short:-G	long:--ghq	desc:Show ghq path	func:ghq list	condition:which ghq	format:$HOME/src/%
```
These lines are not full path (on gif video) but it's done with no error. Because enhancd formats the selected path base on `format` before passing cd command.
> Add 'format' label to format custom input before passing cd

- functions/_enhancd_filepath_walk.fish
- functions/_enhancd_filter_interactive.fish
- functions/enhancd.fish
- src/filepath.sh
fixed some bugs I and [several others](https://github.com/b4b4r07/enhancd/issues/200) encountered after the latest update
- Apple M1 macOS Ventura 13.2.1, iTerm2 3.4.19, fish 3.6.1, fisher 4.4.3, tide 5.5.1
I was unable to `cd` without seeing errors 😵‍💫
```
~/.config/fish/functions/enhancd.fish (line 58): Missing end to balance this if statement
if _enhancd_helper_is_default_flag "$argv[1]"
^^
from sourcing file ~/.config/fish/functions/enhancd.fish
called on line 1 of file ~/.config/fish/conf.d/enhancd.fish
in function 'cd' with arguments '../'
source: Error while reading file '/Users/peeviddy/.config/fish/functions/enhancd.fish'
fish: Unknown command: enhancd
~/.config/fish/conf.d/enhancd.fish (line 3):
enhancd $argv
^~~~~~^
in function 'cd' with arguments '../'
```
thanks to …
> fix fish errors

- src/filepath.sh
this current behavior
```
+__enhancd::filepath::walk:6> dirs=( /etc/apache2 $'/etc\n/' ) 
```
shoule be
```
+__enhancd::filepath::walk:6> dirs=( /etc/apache2 /etc ) 
````
https://github.com/b4b4r07/enhancd/issues/209 (Especially https://github.com/b4b4r07/enhancd/issues/209#issuecomment-1526928287)
> Do not quote multiple lines to deal as single line

- functions/_enhancd_filter_interactive.fish
Fixes https://github.com/babarot/enhancd/issues/207
Single results are still showing the filter.
> Single results are still showing the filter #207

- functions/_enhancd_source_history.fish
- functions/enhancd/lib/cdpath.awk
- src/sources.sh
Make enhancd aware of the `CDPATH`.
Currently when cd'ing with a folder that exists under the current current working directory enhancd enters that directory instead of pulling up the history widget. This change extends that to also check if the folder is under any of the paths listed in `CDPATH`, and enters the first found and skips the history widget.
> Use CDPATH if set

- src/filepath.sh
Updates IFS before getting parent directory
Fixes #222
> fix: parent directory containing spaces (#222)
